### ISSUE TITLE
Where can I ask for help for SparkCLR

### ISSUE THREAD

**Issue by nkiranrao** [Microsoft/SparkCLR#204]
I have asked a question on  [stackoverflow here] ( http://stackoverflow.com/questions/34614963/using-dataframes-created-in-sparkclr-with-zeppelin-queries ) but looks like there are no followers for the `sparkclr` tag. I was wondering where can we request for help on using this? 

Thanks
Kiran

**Comment by skaarthik** [comment]
Hi Kiran - thanks for checking. Some of us in SparkCLR dev team look for posts in StackOverflow on SparkCLR and C# with Spark in a regular cadence. Since sparkclr tag didn't even exist until few days back, we could not subscribe to it. Based on my quick research adding tags is allowed only at the time of posting a question and I personally did not want to post a SO question just for the purpose of creating a tag. Now that it is available, I have just subscribed myself to sparclr tag. I assume other committers/contributors will do the same to respond to StackOverflow questions in a timely manner.

StackOverflow, GitHub and our user mailing list (sparkclr-user@googlegroups.com) are good forums to ask questions. We will respond to your post in StackOverflow today.
